name: caso2
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/backend
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - user=${user}
      - pass=${pass}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
    #tty: true
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend/:/frontend
  database:
    image: database
    container_name: database
    build:
      context: ./database
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - 5432:5432
  proxy:
    image: proxy
    container_name: proxy
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/myconf.template:/etc/nginx/templates/default.conf.template
      - ./proxy/certs:/etc/nginx/certs

    environment:
      - FRONT_PORT=4200
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - frontend
      - backend
